name: app_ffi
description: A Flutter app ffi project
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.xin1t.app_ffi
    pluginClass: AppFfiPlugin
