name: app_base
description: app base package project.
version: 0.0.1
author: 616782041@qq.com
homepage: https://xinfeng-tech.github.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
